ALTER TABLE `PagamentoVendas`
  MODIFY `metodo` ENUM('PIX','DINHEIRO','CARTAO','CREDIARIO','BOLETO','TRANSFERENCIA','CHEQUE','CREDITO','DEBITO','GATEWAY','OUTRO') NOT NULL DEFAULT 'PIX';

ALTER TABLE `CaixaMovimento`
  MODIFY `metodoPagamento` ENUM('PIX','DINHEIRO','CARTAO','CREDIARIO','BOLETO','TRANSFERENCIA','CHEQUE','CREDITO','DEBITO','GATEWAY','OUTRO') NULL;

ALTER TABLE `LancamentoFinanceiro`
  MODIFY `formaPagamento` ENUM('PIX','DINHEIRO','CARTAO','CREDIARIO','BOLETO','TRANSFERENCIA','CHEQUE','CREDITO','DEBITO','GATEWAY','OUTRO') NOT NULL;

ALTER TABLE `ParcelaFinanceiro`
  MODIFY `formaPagamento` ENUM('PIX','DINHEIRO','CARTAO','CREDIARIO','BOLETO','TRANSFERENCIA','CHEQUE','CREDITO','DEBITO','GATEWAY','OUTRO') NULL;
