import { Router, type RequestHandler } from "express";
import multer from "multer";
import { bulkCatalogItems, cancelPublicOrder, createManualOrder, createPublicOrder, createTableOrder, deleteCatalogItemImage, finishTableCleaning, getConfig, getOnlineOrderingStatus, listCatalog, listCatalogProducts, listDeliveryZones, listKdsTickets, listOptionGroups, listOrders, listProductionCategories, listProductionPoints, listTables, openTableSession, previewPublicCheckout, publicMenu, publicTracking, releaseTable, saveCatalogItem, saveConfig, saveDeliveryZone, saveOnlineOrderingStatus, saveOptionGroup, saveProductionPoint, saveTable, transitionKdsTicket, transitionOrder, uploadCatalogItemImage, waitTableBill } from "../../controllers/restaurante/restaurante";
import { deleteRestaurantAccountAddress, getRestaurantAccount, loginRestaurantAccount, registerRestaurantAccount, saveRestaurantAccountAddress, updateRestaurantAccount } from "../../controllers/restaurante/customer";
import { authenticateJWT } from "../../middlewares/auth";
import { optionalRestaurantCustomer, requireRestaurantCustomer } from "../../middlewares/restaurantCustomerAuth";
import { requireRestauranteAccess, requireRestauranteModule } from "../../middlewares/restauranteAccess";
import { listPrintJobs, listPrintRules, listPrintStations, regeneratePrintStationToken, reprintOrder, reprintProductionTicket, savePrintRule, savePrintStation, stationAckJob, stationClaimJobs, stationHeartbeat } from "../../controllers/restaurante/printing";
import { currentRestaurantAccess, listRestaurantUserRoles, saveRestaurantUserRoles } from "../../controllers/restaurante/access";
import { deleteFidelityProgram, fidelityOptions, getFidelityProgram, saveFidelityProgram } from "../../controllers/restaurante/loyalty";
import { acceptDelivery, directDelivery, driverContext, driverDeliveryHistory, listDeliveryDispatch, offerDelivery, publishDriverLocation, updateDeliveryStatus, updateDriverAvailability } from "../../controllers/restaurante/delivery";
import { restaurantDashboard } from "../../controllers/restaurante/dashboard";
import { requireRestauranteEntregador } from "../../middlewares/restauranteEntregador";

export const routerRestaurante = Router();
const use = (handler: unknown) => handler as RequestHandler;
const uploadCatalogImage = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });

routerRestaurante.get("/publico/:slug/cardapio", optionalRestaurantCustomer, use(publicMenu));
routerRestaurante.post("/publico/:slug/checkout/previa", use(previewPublicCheckout));
routerRestaurante.post("/publico/:slug/pedidos", optionalRestaurantCustomer, use(createPublicOrder));
routerRestaurante.get("/publico/pedidos/:token", use(publicTracking));
routerRestaurante.post("/publico/pedidos/:token/cancelamento", use(cancelPublicOrder));
routerRestaurante.post("/publico/:slug/conta/cadastro", use(registerRestaurantAccount));
routerRestaurante.post("/publico/:slug/conta/login", use(loginRestaurantAccount));
routerRestaurante.get("/publico/:slug/conta", requireRestaurantCustomer, use(getRestaurantAccount));
routerRestaurante.patch("/publico/:slug/conta", requireRestaurantCustomer, use(updateRestaurantAccount));
routerRestaurante.post("/publico/:slug/conta/enderecos", requireRestaurantCustomer, use(saveRestaurantAccountAddress));
routerRestaurante.put("/publico/:slug/conta/enderecos/:id", requireRestaurantCustomer, use(saveRestaurantAccountAddress));
routerRestaurante.delete("/publico/:slug/conta/enderecos/:id", requireRestaurantCustomer, use(deleteRestaurantAccountAddress));
routerRestaurante.post("/estacao-impressao/heartbeat", use(stationHeartbeat));
routerRestaurante.get("/estacao-impressao/trabalhos", use(stationClaimJobs));
routerRestaurante.post("/estacao-impressao/trabalhos/ack", use(stationAckJob));

routerRestaurante.use(authenticateJWT);
// PWA dedicada: apenas usuarios explicitamente vinculados ao papel ENTREGADOR.
routerRestaurante.get("/entregador/contexto", requireRestauranteEntregador(), use(driverContext));
routerRestaurante.get("/entregador/historico", requireRestauranteEntregador(), use(driverDeliveryHistory));
routerRestaurante.put("/entregador/disponibilidade", requireRestauranteEntregador(), use(updateDriverAvailability));
routerRestaurante.post("/entregador/entregas/:pedidoId/aceitar", requireRestauranteEntregador(), use(acceptDelivery));
routerRestaurante.post("/entregador/entregas/:pedidoId/status", requireRestauranteEntregador(), use(updateDeliveryStatus));
routerRestaurante.post("/entregador/entregas/:pedidoId/localizacao", requireRestauranteEntregador(), use(publishDriverLocation));
routerRestaurante.get("/acesso", requireRestauranteModule(), use(currentRestaurantAccess));
routerRestaurante.get("/pedidos-online", requireRestauranteModule(), use(getOnlineOrderingStatus));
routerRestaurante.put("/pedidos-online", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveOnlineOrderingStatus));
routerRestaurante.get("/usuarios-papeis", requireRestauranteAccess("PAPEIS_GERENCIAR"), use(listRestaurantUserRoles));
routerRestaurante.put("/usuarios-papeis/:usuarioId", requireRestauranteAccess("PAPEIS_GERENCIAR"), use(saveRestaurantUserRoles));
routerRestaurante.get("/configuracao", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(getConfig));
routerRestaurante.put("/configuracao", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveConfig));
routerRestaurante.get("/fidelidade", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(getFidelityProgram));
routerRestaurante.post("/fidelidade", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveFidelityProgram));
routerRestaurante.put("/fidelidade/:id", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveFidelityProgram));
routerRestaurante.delete("/fidelidade/:id", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(deleteFidelityProgram));
routerRestaurante.get("/fidelidade/opcoes", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(fidelityOptions));
routerRestaurante.get("/cardapio", requireRestauranteAccess("CARDAPIO_VISUALIZAR"), use(listCatalog));
routerRestaurante.get("/cardapio/produtos", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(listCatalogProducts));
routerRestaurante.post("/cardapio", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(saveCatalogItem));
routerRestaurante.post("/cardapio/acoes-em-massa", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(bulkCatalogItems));
routerRestaurante.patch("/cardapio/:id", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(saveCatalogItem));
routerRestaurante.post("/cardapio/:id/imagem", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), uploadCatalogImage.single("file"), use(uploadCatalogItemImage));
routerRestaurante.delete("/cardapio/:id/imagem", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(deleteCatalogItemImage));
routerRestaurante.get("/grupos-opcoes", requireRestauranteAccess("CARDAPIO_VISUALIZAR"), use(listOptionGroups));
routerRestaurante.post("/grupos-opcoes", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(saveOptionGroup));
routerRestaurante.patch("/grupos-opcoes/:id", requireRestauranteAccess("CARDAPIO_CONFIGURAR"), use(saveOptionGroup));
routerRestaurante.get("/zonas-entrega", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(listDeliveryZones));
routerRestaurante.post("/zonas-entrega", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveDeliveryZone));
routerRestaurante.patch("/zonas-entrega/:id", requireRestauranteAccess("CONFIGURACOES_GERENCIAR"), use(saveDeliveryZone));
routerRestaurante.get("/mesas", requireRestauranteAccess("SALAO_VISUALIZAR"), use(listTables));
routerRestaurante.post("/mesas", requireRestauranteAccess("SALAO_CONFIGURAR"), use(saveTable));
routerRestaurante.patch("/mesas/:id", requireRestauranteAccess("SALAO_CONFIGURAR"), use(saveTable));
routerRestaurante.post("/mesas/:id/abrir", requireRestauranteAccess("SALAO_OPERAR"), use(openTableSession));
routerRestaurante.post("/mesas/:id/aguardar-conta", requireRestauranteAccess("SALAO_OPERAR"), use(waitTableBill));
routerRestaurante.post("/mesas/:id/liberar", requireRestauranteAccess("SALAO_OPERAR"), use(releaseTable));
routerRestaurante.post("/mesas/:id/finalizar-limpeza", requireRestauranteAccess("SALAO_OPERAR"), use(finishTableCleaning));
routerRestaurante.post("/sessoes-mesa/:id/pedidos", requireRestauranteAccess("SALAO_OPERAR"), use(createTableOrder));
routerRestaurante.get("/pontos-producao/categorias", requireRestauranteAccess("KDS_VISUALIZAR"), use(listProductionCategories));
routerRestaurante.get("/pontos-producao", requireRestauranteAccess("KDS_VISUALIZAR"), use(listProductionPoints));
routerRestaurante.post("/pontos-producao", requireRestauranteAccess("KDS_CONFIGURAR"), use(saveProductionPoint));
routerRestaurante.patch("/pontos-producao/:id", requireRestauranteAccess("KDS_CONFIGURAR"), use(saveProductionPoint));
routerRestaurante.get("/kds", requireRestauranteAccess("KDS_VISUALIZAR"), use(listKdsTickets));
routerRestaurante.post("/kds/:id/transicao", requireRestauranteAccess("KDS_OPERAR"), use(transitionKdsTicket));
routerRestaurante.get("/estacoes-impressao", requireRestauranteAccess("IMPRESSAO_VISUALIZAR"), use(listPrintStations));
routerRestaurante.post("/estacoes-impressao", requireRestauranteAccess("IMPRESSAO_CONFIGURAR"), use(savePrintStation));
routerRestaurante.patch("/estacoes-impressao/:id", requireRestauranteAccess("IMPRESSAO_CONFIGURAR"), use(savePrintStation));
routerRestaurante.post("/estacoes-impressao/:id/regenerar-token", requireRestauranteAccess("IMPRESSAO_CONFIGURAR"), use(regeneratePrintStationToken));
routerRestaurante.get("/regras-impressao", requireRestauranteAccess("IMPRESSAO_VISUALIZAR"), use(listPrintRules));
routerRestaurante.put("/regras-impressao", requireRestauranteAccess("IMPRESSAO_CONFIGURAR"), use(savePrintRule));
routerRestaurante.get("/trabalhos-impressao", requireRestauranteAccess("IMPRESSAO_VISUALIZAR"), use(listPrintJobs));
routerRestaurante.post("/kds/:id/reimprimir", requireRestauranteAccess("KDS_OPERAR"), use(reprintProductionTicket));
routerRestaurante.get("/pedidos", requireRestauranteAccess("PEDIDOS_VISUALIZAR"), use(listOrders));
routerRestaurante.post("/pedidos", requireRestauranteAccess("PEDIDOS_OPERAR"), use(createManualOrder));
routerRestaurante.get("/painel", requireRestauranteAccess("PEDIDOS_VISUALIZAR"), use(restaurantDashboard));
routerRestaurante.post("/pedidos/:id/transicao", requireRestauranteAccess("PEDIDOS_OPERAR"), use(transitionOrder));
routerRestaurante.post("/pedidos/:id/imprimir", requireRestauranteAccess("IMPRESSAO_VISUALIZAR"), use(reprintOrder));
routerRestaurante.get("/entregas/despacho", requireRestauranteAccess("PEDIDOS_VISUALIZAR"), use(listDeliveryDispatch));
routerRestaurante.post("/entregas/:pedidoId/ofertar", requireRestauranteAccess("PEDIDOS_OPERAR"), use(offerDelivery));
routerRestaurante.post("/entregas/:pedidoId/direcionar", requireRestauranteAccess("PEDIDOS_OPERAR"), use(directDelivery));
