import { Router } from "express";
import { routerProdutos } from "./produtos/router";
import { routerContas } from "./contas/router";
import { routerClientes } from "./clientes/router";
import { routerVendas } from "./vendas/router";
import { monitorRouter } from "./monitor/router";
import { routerLancamentos } from "./lancamentos/router";
import routerUploads from "./uploads/router";
import { routerUsuarios } from "./administracao/usuarios/router";
import { routerGerencia } from "./gerencia/router";
import { routerServicos } from "./servicos/router";
import { routerDefault } from "./default";
import { routerAdminMain } from "./administracao/router";
import { routerArena } from "./arena/router";
import { routerAssinaturas } from "./assinaturas/router";
import { routerWhatsapp } from "./whatsapp/router";
import { routerInformativos } from "./informativos/router";
import { routerComandas } from "./comandas/router";
import { routerMetas } from "./metas/router";
import { routerLoja } from "./loja/router";
import { callChatGemini } from "../controllers/inteligence/gemini";
import { routerIa } from "./ia/router";
import { authenticateJWT } from "../middlewares/auth";

const RouterMain = Router();

RouterMain.use(routerDefault);
RouterMain.use("/api/contas", routerContas);
RouterMain.use("/api/produtos", routerProdutos);
RouterMain.use("/api/servicos", routerServicos);
RouterMain.use("/api/usuarios", routerUsuarios);
RouterMain.use("/api/clientes", routerClientes);
RouterMain.use("/api/gerencia", routerGerencia);
RouterMain.use("/api/lancamentos", routerLancamentos);
RouterMain.use("/api/vendas", routerVendas);
RouterMain.use("/api/system", monitorRouter);
RouterMain.use("/api/uploads", routerUploads);
RouterMain.use("/api/admin", routerAdminMain);
RouterMain.use("/api/arenas", routerArena);
RouterMain.use("/api/assinaturas", routerAssinaturas);
RouterMain.use("/api/whatsapp", routerWhatsapp);
RouterMain.use("/api/informativos", routerInformativos);
RouterMain.use("/api/comandas", routerComandas);
RouterMain.use("/api/metas", routerMetas);
RouterMain.use("/api/loja", routerLoja);
RouterMain.post("/api/gemini/chat", authenticateJWT, callChatGemini);
RouterMain.use("/api/ia", routerIa);

export { RouterMain };
