ALTER TABLE `OuriveEvento`
  MODIFY `tipo` ENUM('RECEBIMENTO','FOTO','ORCAMENTO','APROVACAO','RECUSA','RESPONSAVEL','MATERIAL','ETAPA','REVISAO','ENTREGA','CANCELAMENTO','FINANCEIRO','CUSTO_EXTRA') NOT NULL;
