-- CreateTable
CREATE TABLE `OuriveUsuarioPapel` (`contaId` INTEGER NOT NULL, `usuarioId` INTEGER NOT NULL, `papel` ENUM('GESTOR','ATENDIMENTO','OURIVE','REVISAO') NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`usuarioId`, `papel`), INDEX `OuriveUsuarioPapel_contaId_papel_idx`(`contaId`, `papel`));
CREATE TABLE `OuriveEspecialidade` (`id` INTEGER NOT NULL AUTO_INCREMENT, `contaId` INTEGER NOT NULL, `nome` VARCHAR(191) NOT NULL, `descricao` TEXT NULL, `ativo` BOOLEAN NOT NULL DEFAULT true, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `OuriveEspecialidade_contaId_nome_key`(`contaId`, `nome`));
CREATE TABLE `OuriveUsuarioEspecialidade` (`contaId` INTEGER NOT NULL, `usuarioId` INTEGER NOT NULL, `especialidadeId` INTEGER NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`usuarioId`, `especialidadeId`), INDEX `OuriveUsuarioEspecialidade_contaId_especialidadeId_idx`(`contaId`, `especialidadeId`));
CREATE TABLE `OuriveConfiguracao` (`contaId` INTEGER NOT NULL, `receitaCategoriaId` INTEGER NULL, `receitaContaFinanceiraId` INTEGER NULL, `comissaoCategoriaId` INTEGER NULL, `comissaoContaFinanceiraId` INTEGER NULL, `prazoAprovacaoDias` INTEGER NOT NULL DEFAULT 7, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`contaId`));
CREATE TABLE `OuriveOrdem` (`id` INTEGER NOT NULL AUTO_INCREMENT, `contaId` INTEGER NOT NULL, `ordemServicoId` INTEGER NOT NULL, `status` ENUM('RECEBIDA','ORCAMENTO','PRODUCAO','REVISAO','ENTREGUE','RECUSADA','CANCELADA') NOT NULL DEFAULT 'RECEBIDA', `codigoRastreio` VARCHAR(191) NOT NULL, `custoExtra` DECIMAL(10,2) NOT NULL DEFAULT 0, `receitaLancamentoId` INTEGER NULL, `faturadaEm` DATETIME(3) NULL, `entregueEm` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `OuriveOrdem_ordemServicoId_key`(`ordemServicoId`), UNIQUE INDEX `OuriveOrdem_codigoRastreio_key`(`codigoRastreio`), UNIQUE INDEX `OuriveOrdem_receitaLancamentoId_key`(`receitaLancamentoId`), INDEX `OuriveOrdem_contaId_status_idx`(`contaId`, `status`));
CREATE TABLE `OurivePeca` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `descricao` TEXT NOT NULL, `metal` VARCHAR(191) NULL, `pedras` TEXT NULL, `pesoInformado` DECIMAL(10,3) NULL, `estadoConservacao` TEXT NULL, `checklistRecebimento` JSON NULL, `codigoRastreio` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `OurivePeca_ordemOuriveId_codigoRastreio_key`(`ordemOuriveId`, `codigoRastreio`));
CREATE TABLE `OurivePecaFoto` (`id` INTEGER NOT NULL AUTO_INCREMENT, `pecaId` INTEGER NOT NULL, `url` TEXT NOT NULL, `descricao` TEXT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), INDEX `OurivePecaFoto_pecaId_idx`(`pecaId`));
CREATE TABLE `OuriveOrcamento` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `versao` INTEGER NOT NULL, `servicos` JSON NOT NULL, `desconto` DECIMAL(10,2) NOT NULL DEFAULT 0, `prazoPrevisto` DATETIME(3) NULL, `custoEstimado` DECIMAL(10,2) NOT NULL DEFAULT 0, `valorFinal` DECIMAL(10,2) NOT NULL, `enviadoEm` DATETIME(3) NULL, `aprovadoEm` DATETIME(3) NULL, `recusadoEm` DATETIME(3) NULL, `aprovacaoOrigem` VARCHAR(191) NULL, `aprovacaoObservacao` TEXT NULL, `tokenHash` VARCHAR(191) NULL, `tokenExpiraEm` DATETIME(3) NULL, `invalidoEm` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE INDEX `OuriveOrcamento_ordemOuriveId_versao_key`(`ordemOuriveId`, `versao`), UNIQUE INDEX `OuriveOrcamento_tokenHash_key`(`tokenHash`), INDEX `OuriveOrcamento_ordemOuriveId_enviadoEm_idx`(`ordemOuriveId`, `enviadoEm`));
CREATE TABLE `OuriveEtapa` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `nome` VARCHAR(191) NOT NULL, `especialidadeId` INTEGER NULL, `prazoPrevisto` DATETIME(3) NULL, `observacao` TEXT NULL, `status` ENUM('PENDENTE','EM_EXECUCAO','AGUARDANDO_REVISAO','APROVADA','REPROVADA') NOT NULL DEFAULT 'PENDENTE', `iniciadaEm` DATETIME(3) NULL, `finalizadaEm` DATETIME(3) NULL, `revisadaEm` DATETIME(3) NULL, `revisadaPorId` INTEGER NULL, `motivoReprovacao` TEXT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`id`), INDEX `OuriveEtapa_ordemOuriveId_status_idx`(`ordemOuriveId`, `status`));
CREATE TABLE `OuriveEtapaResponsavel` (`etapaId` INTEGER NOT NULL, `usuarioId` INTEGER NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`etapaId`, `usuarioId`));
CREATE TABLE `OuriveMaterial` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `pecaId` INTEGER NULL, `produtoId` INTEGER NOT NULL, `quantidadePlanejada` INTEGER NOT NULL, `quantidadeConsumida` INTEGER NOT NULL DEFAULT 0, `quantidadeDevolvida` INTEGER NOT NULL DEFAULT 0, `custoSnapshot` DECIMAL(10,2) NULL, `consumidoEm` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), INDEX `OuriveMaterial_ordemOuriveId_produtoId_idx`(`ordemOuriveId`, `produtoId`));
CREATE TABLE `OuriveComissao` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `etapaId` INTEGER NOT NULL, `usuarioId` INTEGER NOT NULL, `tipo` ENUM('PERCENTUAL','VALOR_FIXO') NOT NULL, `referencia` DECIMAL(10,2) NOT NULL, `valorConsolidado` DECIMAL(10,2) NULL, `consolidadaEm` DATETIME(3) NULL, `lancamentoFinanceiroId` INTEGER NULL, `quitadaEm` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE INDEX `OuriveComissao_lancamentoFinanceiroId_key`(`lancamentoFinanceiroId`), INDEX `OuriveComissao_ordemOuriveId_usuarioId_idx`(`ordemOuriveId`, `usuarioId`));
CREATE TABLE `OuriveEvento` (`id` INTEGER NOT NULL AUTO_INCREMENT, `ordemOuriveId` INTEGER NOT NULL, `tipo` ENUM('RECEBIMENTO','FOTO','ORCAMENTO','APROVACAO','RECUSA','RESPONSAVEL','MATERIAL','ETAPA','REVISAO','ENTREGA','CANCELAMENTO','FINANCEIRO','CUSTO_EXTRA') NOT NULL, `descricao` TEXT NOT NULL, `dados` JSON NULL, `autorId` INTEGER NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), INDEX `OuriveEvento_ordemOuriveId_createdAt_idx`(`ordemOuriveId`, `createdAt`));
