-- AlterTable
ALTER TABLE `ArenaAgendamentosPagamentos` MODIFY `metodoPagamento` ENUM('PIX', 'DINHEIRO', 'CARTAO', 'CREDIARIO', 'BOLETO', 'TRANSFERENCIA', 'CHEQUE', 'CREDITO', 'DEBITO', 'GATEWAY', 'OUTRO') NOT NULL DEFAULT 'PIX';

-- AlterTable
ALTER TABLE `AssinaturaPagar` MODIFY `formaPagamento` ENUM('PIX', 'DINHEIRO', 'CARTAO', 'CREDIARIO', 'BOLETO', 'TRANSFERENCIA', 'CHEQUE', 'CREDITO', 'DEBITO', 'GATEWAY', 'OUTRO') NULL;

-- AlterTable
ALTER TABLE `ComandaPagamento` MODIFY `formaPagamento` ENUM('PIX', 'DINHEIRO', 'CARTAO', 'CREDIARIO', 'BOLETO', 'TRANSFERENCIA', 'CHEQUE', 'CREDITO', 'DEBITO', 'GATEWAY', 'OUTRO') NOT NULL;
