-- AlterTable
ALTER TABLE `Vendas` ADD COLUMN `garantia` INTEGER NULL DEFAULT 0,
    ADD COLUMN `status` ENUM('ORCAMENTO', 'FATURADO', 'ANDAMENTO', 'FINALIZADO', 'PENDENTE', 'CANCELADO') NOT NULL DEFAULT 'ORCAMENTO',
    ADD COLUMN `vendedorId` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `Vendas` ADD CONSTRAINT `Vendas_vendedorId_fkey` FOREIGN KEY (`vendedorId`) REFERENCES `Usuarios`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
